### ISSUE TITLE
PoP for Wallet Instance Attestation during the Issuance phase

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#101]
In the issuance request we use the WIA and we implicitly assume that the public part of the key contained in the WIA (cnf.jwk) must be used to verify the signature of the issuance request

reading the text we didn't find any normative or explicit text about this.

This issue will be resolved by the PR that brings the normative language and the description about how the PoP is appliad on the WIA during the issuance phase

**Comment by fmarino-ipzs** [comment]
We are working on a PR that brings the normative language into the section. As soon as we make the PR we will resolve this issue.
@asharif1990 @giadas

**Comment by peppelinux** [comment]
Fixed by https://github.com/italia/eudi-wallet-it-docs/pull/126
