### ISSUE TITLE
Credential Request Client Assertion Type

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#102]
- [ ] `client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-key-attestation` doesn't exist in the [IANA Registry](https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml) and in the vcstuff drafts, like [OAuth 2.0 Attestation-Based Client Authentication](https://vcstuff.github.io/draft-ietf-oauth-attestation-based-client-auth/draft-ietf-oauth-attestation-based-client-auth.html).

Do you have any ref to the draft where the current client_attestation_type is defined?

If not, I suggest to change it to `urn:ietf:params:oauth:client-assertion-type:jwt-bearer` or `urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation`

**Comment by peppelinux** [comment]
Please note that in the current example in the specs the client_assertion is missing

````
{
"response_type":"code",
"client_id":"$thumprint-of-the-jwk-in-the-cnf-wallet-attestation$",
"state":"fyZiOL9Lf2CeKuNT2JzxiLRDink0uPcd",
"code_challenge":"E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM",
"code_challenge_method":"S256",
"authorization_details":[
{
    "type":"openid_credential",
    "format": "vc+sd-jwt",
    "credential_definition": {
        "type": ["PersonIdentificationData"]
    }
}
],
"redirect_uri":"eudiw://start.wallet.example.org",
"client_assertion_type":"urn:ietf:params:oauth:client-assertion-type:jwt-key-attestation",
}
````

**Comment by fmarino-ipzs** [comment]
The value was taken from a OAuth 2.0 Attestation-Based Client Authentication draft but in the meantime was changed. 
https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/pull/11/files

I'm in favour of  `urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation`.
