### ISSUE TITLE
Wallet Instance request media type

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#105]
@rohe 's

`var+jwt` (Verifiable Assertion Request JWT) are there other Verifiable Assertion Request then a Wallet Instance Attestation Request?
If so I'd rather have `wiar+jwt` as the header `typ` for a Wallet Instance Attestation Request.

We should be as specific as necessary.

**Comment by grausof** [comment]
@peppelinux what do you think? 
`wiar` was the value we previously had and then you asked to change to `var+jwt`

CC @fmarino-ipzs

**Comment by peppelinux** [comment]
@grausof if it's as you mentioned then the PR is up to me, consider it done
