### ISSUE TITLE
Wallet Instance Attestation response, normative definitions and non normative example

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#107]
@rohe 's

In https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/wallet-instance-attestation.rst there is an example on how to Obtain a Wallet Instance Attestation. But only the request part is shown, there is no example of the response part.

@peppelinux 's 

We need a normative text and a non normative example of the response

**Comment by grausof** [comment]
Fixed in: https://github.com/italia/eudi-wallet-it-docs/pull/115
