### ISSUE TITLE
Describe the wallet instance lifecycle, the interaction between the wallet instance and the wallet provider

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#110]
@rohe 's

In the description of the wallet instance lifecycle the interaction between the wallet instance and the wallet provider is omitted. Shouldn't it be part of the initialization process ? This is in https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/wallet-solution.rst

**Comment by grausof** [comment]
The interaction between the wallet instance and the wallet provider is described in the [Wallet Instance Attestation paragraph](https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/wallet-instance-attestation.rst#dynamic-component-view) along with a sequence diagram as well.
