### ISSUE TITLE
ECDH-ES response encryption

### ISSUE THREAD

**Issue by alenhorvat** [italia/eidas-it-wallet-docs#112]
Hi,

Any plans to support ECDH-ES encrypted authentication response? (https://github.com/italia/eudi-wallet-it-docs/blob/12cab613529e913bbf3473d6e558bb025c760d8b/docs/en/relying-party-solution.rst?plain=1#L697)
I'm asking since ISO mDL 18013-7 uses the algorithm as a default algorithm.

Thank you!

**Comment by peppelinux** [comment]
Included here: https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/algorithms.rst?plain=1#L81
