### ISSUE TITLE
[Relying Party] Discovery section

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#116]
As I mentioned in the PR #100 we should add a new section describing the discovery phase also providing the non-normative examples. 
Maybe we should do the same for the relying party section as well.

**Comment by fmarino-ipzs** [comment]
I move this issue to the milestone 0.7

**Comment by peppelinux** [comment]
Already there: https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/remote-flow.rst?plain=1#L19

in both high and detailed levels
