### ISSUE TITLE
how the PID issuer get hold of the public key

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#119]
@rohe 's

In https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/pid-eaa-issuance.rst#high-level-pid-flow third bullet point (well actually fourth, but it has number 3) it says :

"A fresh key pairs is generated by the Wallet Instance, the public key is used by PID Provider for the key binding of the PID." 

but it doesn't say how the PID issuer get hold of the public key.
I though the PID issuer where supposed to use the 'cnf' key in the wallet instance attestation signed by the wallet provider ?

**Comment by peppelinux** [comment]
Partially resolved by https://github.com/italia/eudi-wallet-it-docs/pull/121

**Comment by fmarino-ipzs** [comment]
The PID is bound to a new fresh key (and not to the `cnf ` key). The `proof ` parameter contains the key material the new credential shall be bound to, according to [here](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-request).

**Comment by peppelinux** [comment]
@rohe 's

Well, I'm OK with the meaning of the answer but I still think you could be more explicit in the text about how the whole thing is supposed to work. A specific reference to section 7.2 for instance.
Or even to step 19 of the detailed flow.

**Comment by fmarino-ipzs** [comment]
Yes I agree, we are finalizing a PR with additional normative details about the issuance flow. We will go through this issue there.
@asharif1990 
@giadas

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-docs/issues/119#issuecomment-1712129254
