### ISSUE TITLE
Security requirements 

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#125]
I propose to map the security requirements defined in https://github.com/openid/OpenID4VC_SecTrust within the sections of this documentation, giving guidance about how the security #code defined in oid4vc-security-and-trust is satisfied

**Comment by Sh-Amir** [comment]
> I propose to map the security requirements defined in https://vcstuff.github.io/oid4vc-security-and-trust/draft-oid4vc-security-and-trust.html within the sections of this documentation, giving guidance about how the security #code defined in oid4vc-security-and-trust is satisfied

This is actually on our to-do list specifically on the PID/(Q)EAA issuance. I plan to explain how our design choices can satisfy the requirements that we extracted from eIDAS 2.0, ARF, and oid4vc-security-and-trust documents. 
@giadas @fmarino-ipzs

**Comment by peppelinux** [comment]
moved here
https://github.com/openid/OpenID4VC_SecTrust
