### ISSUE TITLE
client_assertion_type urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation and PAR endpoint

### ISSUE THREAD

**Issue by siriusblock** [italia/eidas-it-wallet-docs#130]
In [Pushed Authorization Request Section](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/pid-eaa-issuance.html#pushed-authorization-request-endpoint) client_assertion_type is set to urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation and the ref. doc is [Assertion Framework for OAuth 2.0 Client Authentication and Authorization Grants](https://www.rfc-editor.org/rfc/rfc7521) This document does not mention client assertion type urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation but another extending ref. doc does - namely [OAuth 2.0 Attestation-Based Client Authentication ](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#name-sub-namespace-registration-)

PAR endpoint is a protected endpoint. Correct me if I'm wrong the client authentication is done by validating the JWT signature, that is passed to request parameter, to the public key provided in wallet instance attestation cnf claim that is passed to client_assertion parameter. But [OAuth 2.0 Attestation-Based Client Authentication ](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#name-sub-namespace-registration-) where urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation is defined uses different kind of approach:

"The value of the "client_assertion_type" is "urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation".

The value of the "client_assertion" parameter contains two JWTs, separated by a ~ character. It MUST NOT contain more or less than precisely two JWTs seperated by the '~' character. The first JWT MUST be the client attestation JWT defined in [Section 4.1.1](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#client-attestation-jwt), the second JWT MUST the client attestation PoP defined in [Section 4.1.2](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#client-attestation-pop-jwt)."

Can you please comment on this!

**Comment by peppelinux** [comment]
Yes it uses `urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation` by mentioning RFC7521 even is `urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation` is defined in "OAuth 2.0 Attestation-Based Client Authentication"

"OAuth 2.0 Attestation-Based Client Authentication" extends RFC7521:

````
[[RFC7521](https://www.rfc-editor.org/rfc/rfc7521)] defines a way for a client to include an assertion in a token request to an authorization server for the purposes of client authentication. This specification uses this framework to define a new assertion type that provides a way for a client instance to authenticate itself with the authorization server through an assertion that is bound to a public key (for proof of possession).
````

Probably your question is related to the issuance flow.

The PoP at the PAR endpoint is achieved using the cnf.jwk issued within the `client_assertion=$WalletInstanceAttestation$` for the signature validation of the `request=eyJhbGciOiJSUzI1NiIsImtpZCI6ImsyYmRjIn0.ew0KIC Jpc3MiOiAiczZCaGRSa3F0MyIsDQogImF1ZCI6ICJodHRwczovL3NlcnZlci5leGFtcGxlLmNvbSIsDQo gInJlc3BvbnNlX3R5cGUiOiAiY29kZSBpZF90b2tlbiIsDQogImNsaWVudF9pZCI6ICJzNkJoZFJrcXQz IiwNCiAicmVkaXJlY3RfdXJpIjogImh0dHBzOi8vY2xpZW50LmV4YW1...`

the signature of the request object proves that the wallet instance is the legitimate owner of the WIA. We find it as simpler than other approaches, and this satisfies the security requirements.

We continue to look forward and with the support of the international community to bring approaches closer and consolidate community specifications. Our approach is requirements-driven and we find OAuth2 as a framework with all be building blocks, already available, to satisfy the requirements

**Comment by peppelinux** [comment]
@siriusblock regarding this

> The value of the "client_assertion" parameter contains two JWTs, separated by a ~ character. It MUST NOT contain more or less than precisely two JWTs seperated by the '~' character. The first JWT MUST be the client attestation JWT defined in [Section 4.1.1](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#client-attestation-jwt), the second JWT MUST the client attestation PoP defined in [Section 4.1.2](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#client-attestation-pop-jwt)."

well, thank you for asking!
I have made clear the statement of the concerns and a proposal that I think may be useful for the discussion, here:
https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/issues/45

Please let us know WDYT

**Comment by siriusblock** [comment]
Both approaches satisfy the requirements, but what is confusing in [Italy's PAR](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/pid-eaa-issuance.html#pushed-authorization-request-endpoint) is that the client_assertion_type is set to urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation. That means client_assertion should be parsed as defined in [OAuth 2.0 Attestation-Based Client Authentication, Section 4.1](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#name-jwt-format-and-processing-r); Should client_assertion_type in Italy's documentation be urn:ietf:params:oauth:client-assertion-type:jwt-bearer? But I guess that is not correct also because [RFC 7523 ](https://datatracker.ietf.org/doc/html/rfc7523#section-3) does not use cnf value from attestation to validate the PoP?

**Comment by Sh-Amir** [comment]
> Both approaches satisfy the requirements, but what is confusing in [Italy's PAR](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/pid-eaa-issuance.html#pushed-authorization-request-endpoint) is that the client_assertion_type is set to urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation. That means client_assertion should be parsed as defined in [OAuth 2.0 Attestation-Based Client Authentication, Section 4.1](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#name-jwt-format-and-processing-r); Should client_assertion_type in Italy's documentation be urn:ietf:params:oauth:client-assertion-type:jwt-bearer? But I guess that is not correct also because [RFC 7523 ](https://datatracker.ietf.org/doc/html/rfc7523#section-3) does not use cnf value from attestation to validate the PoP?

The way that we design the solution is not the standard way that is defined [OAuth 2.0 Attestation-Based Client Authentication, Section 4.1](https://datatracker.ietf.org/doc/html/draft-looker-oauth-attestation-based-client-auth-00#name-jwt-format-and-processing-r). However, at the time we started our design this draft wasn't present that's why we did our design by extending the RFC7521. The confusion that it brings based on the naming is understandable, as we are using the same client_assertion_type as the draft.  Anyway, we are evaluating following the standardized way as defined in the draft after reaching an agreement with the authors of the draft regarding some concerns that we had.

**Comment by siriusblock** [comment]
> Anyway, we are evaluating following the standardized way as defined in the draft after reaching an agreement with the authors of the draft regarding some concerns that we had.

Is this issue discussed in public? gh issue?

**Comment by Sh-Amir** [comment]
> > Anyway, we are evaluating following the standardized way as defined in the draft after reaching an agreement with the authors of the draft regarding some concerns that we had.
> 
> Is this issue discussed in public? gh issue?

Yes, @peppelinux already opened gh issues. One of them is already mentioned in his previous [comment](https://github.com/italia/eudi-wallet-it-docs/issues/130#issuecomment-1732696518).

**Comment by siriusblock** [comment]
So the [Token endpoint](https://italia.github.io/eudi-wallet-it-docs/en/pid-eaa-issuance.html#token-endpoint) authenticates client by using urn:ietf:params:oauth:client-assertion-type:jwt-bearer as client_assertion_type and the client_assertion that is signed using the private key that is created during the setup phase to obtain the Wallet Instance Attestation. 

1) Is the key used to sign client_assertion validated against Wallet Instance Attestation cnf claim that was provided at PAR endpoint?
2) Or there is a plan to use urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation as client_assertion_type and provide Client Attestation JWT (WIA) + Client Attestation JWT PoP as client_assertion?

**Comment by Sh-Amir** [comment]
> So the [Token endpoint](https://italia.github.io/eudi-wallet-it-docs/en/pid-eaa-issuance.html#token-endpoint) authenticates client by using urn:ietf:params:oauth:client-assertion-type:jwt-bearer as client_assertion_type and the client_assertion that is signed using the private key that is created during the setup phase to obtain the Wallet Instance Attestation.
> 
> 1. Is the key used to sign client_assertion validated against Wallet Instance Attestation cnf claim that was provided at PAR endpoint?

> 2. Or there is a plan to use urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation as client_assertion_type and provide Client Attestation JWT (WIA) + Client Attestation JWT PoP as client_assertion?

In the current version, it is the first one. We are using the `private_key_jwt` client authentication method at the token endpoint. The client_assertion is signed using the private key that its public key is asserted in the `cnf` claim.

**Comment by peppelinux** [comment]
Discussion is moved here https://github.com/italia/eudi-wallet-it-docs/issues/131
