### ISSUE TITLE
Issuance callback endpoint

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#137]
See **https://github.com/openid/OpenID4VCI/pull/70**

**Comment by balanza** [comment]
Do you think we will need the feature? We didn't discuss it deeply, I just remember some informal conversations in which we agreed that there's no need for the Issuer to store such information.

**Comment by peppelinux** [comment]
it something discussed on the UX table that required technical coverage, it's not configured in any milestone right now, it requires more analysis and time

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-docs/pull/380
