### ISSUE TITLE
[Issuance flow]: Error Management

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#139]
Error Management Section should be added with a description of the proper error response codes.

**Comment by peppelinux** [comment]
I would rescope this issue with the will to have specialized errors for each endpoint/flow

**Comment by peppelinux** [comment]
This issue should be exploded in five different issues

- [ ] [Wallet Solution] Error Management
- [ ] [Issuance] Error Management
  - here the callback handlers should be taken in account
- [ ] [Presentation] Error Management
- [ ] [Pseudonym] Issuance and Presentation Error Management
- [ ] [Revocation] request and validation Error Management

**Comment by peppelinux** [comment]
linked issue about the requirement to extend the issuance flow with the callback about the status of the stored credential (if any)
https://github.com/italia/eudi-wallet-it-docs/issues/137
