### ISSUE TITLE
Claims presentation for (Q)EAA issuance

### ISSUE THREAD

**Issue by balanza** [italia/eidas-it-wallet-docs#145]
This is a generalization of https://github.com/italia/eudi-wallet-it-docs/issues/144 (PID presentation for (Q)EAA issuance).

We need to define a protocol for the Issuer to claim the User which attributes are needed for the Credential to be issued. We expect the User not to be limited to PID presentation, but to perform a proper credential presentation (which may or may not include PID claims).

This feature is an improvement and is not in scope with our roadmap.

**Comment by peppelinux** [comment]
This statement of the problem is superseeded with the following issue:
https://github.com/italia/eudi-wallet-it-docs/issues/152

It defines the requirements in a more technical way with the aims to give an implementative solution as well.
