### ISSUE TITLE
Defined terms

### ISSUE THREAD

**Issue by misillet** [italia/eidas-it-wallet-docs#16]
https://github.com/italia/eidas-it-wallet-docs/blob/0a918c452512f9b77887b2748b75cffb98579558/docs/en/defined-terms.rst?plain=1#LL1C1-L1C1

**Comment by peppelinux** [comment]
when all the P will be merged, then well catch all the undefined terms updating this section accordingly

**Comment by peppelinux** [comment]
Done here https://github.com/italia/eidas-it-wallet-docs/pull/12
