### ISSUE TITLE
Cryptographic Algorithms

### ISSUE THREAD

**Issue by Sh-Amir** [italia/eidas-it-wallet-docs#164]
The following algorithms are RECOMMENDED to be supported based on [ETSI](https://www.etsi.org/deliver/etsi_ts/119300_119399/119312/01.04.03_60/ts_119312v010403p.pdf) and must complement the list already provided in [Cryptographic Algorithms](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/algorithms.html) section: 

- [x] ES256: ECDSA using one of the following FRP256V1/brainpoolP256r1/p-256 curves and SHA256
- [x] ES384: ECDSA using one of the following brainpoolP384r1/p-384 curves and SHA384
- [x] ES512: ECDSA using one of the following brainpoolP521r1/p-521 curves and SHA521
- [x] PS256: RSASSA-PSS using SHA256 and MGF1 with SHA256
- [x] PS384: RSASSA-PSS using SHA384 and MGF1 with SHA384
- [x] PS512: RSASSA-PSS using SHA521 and MGF1 with SHA521

Notes:

- I did not include EC-SDSA-opt (Schnorr-type digital signature scheme over an elliptic curve) is not commonly used.
- Both SHA2 and SHA3 hash functions can be used with the abovementioned family.
- I did not include EdDSA using one of the following Ed25519/Ed448 curves as it is only reported in [COSE Registry](https://www.iana.org/assignments/cose/cose.xhtml#key-type-parameters).

References:

- [SOGIS-Agreed-Cryptographic-Mechanisms-1.3](https://www.sogis.eu/documents/cc/crypto/SOGIS-Agreed-Cryptographic-Mechanisms-1.3.pdf)
- [Electronic Signatures and Infrastructures (ESI)](https://www.etsi.org/deliver/etsi_ts/119300_119399/119312/01.04.03_60/ts_119312v010403p.pdf)

**Comment by simonebaldiniintesa** [comment]
Hi there.
My understanding is that RS512 is not considered 'not interoperable' or 'not recommended' as for [ ETSI](https://www.etsi.org/deliver/etsi_ts/119300_119399/119312/01.04.03_60/ts_119312v010403p.pdf).
There are other reasons which push for RSA withdrawal?

**Comment by Sh-Amir** [comment]
> Hi there. My understanding is that RS512 is not considered 'not interoperable' or 'not recommended' as for [ ETSI](https://www.etsi.org/deliver/etsi_ts/119300_119399/119312/01.04.03_60/ts_119312v010403p.pdf). There are other reasons which push for RSA withdrawal?

Hi,

here in this list we try to add the missing algorithms which are not refrenced [here](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/algorithms.html). 
RSA algorithms in any case are needed for legacy reasons and in both ETSI and SOG-IS they have mentioned as Legacy algorithms.

**Comment by simonebaldiniintesa** [comment]
Mybe now it's clear the point.
You are actually referring the padding scheme and not the algorithm itself.
RSA PSS is reccomended in ETSI while RSA PKCS1.5 is considered legacy.

**Comment by Sh-Amir** [comment]
> Mybe now it's clear the point. You are actually referring the padding scheme and not the algorithm itself. RSA PSS is reccomended in ETSI while RSA PKCS1.5 is considered legacy.

Yes, exactly. Sorry for not being so precise

**Comment by peppelinux** [comment]
@asharif1990 What about ECDH + HMAC?

I have support of it in Python cryptography

@grausof @balanza @fventola-ipzs ^

**Comment by Sh-Amir** [comment]
> @asharif1990 What about ECDH + HMAC?
> 
> I have support of it in Python cryptography
> 
> @grausof @balanza @fventola-ipzs ^

I don’t have the full knowledge on this and maybe I am not the right person to give the answer.  However if I remember correctly it is used to create a secure channel between the wallet and verifier based on the key shared by ECDH and only will do an HMAC over the data.

**Comment by peppelinux** [comment]
@asharif1990 FYI
https://datatracker.ietf.org/doc/draft-jones-jose-fully-specified-algorithms/

**Comment by peppelinux** [comment]
issue: there are some (obsolete) devices that only supports RSA and not EC in their TEE/StrongBox.

**Comment by fmarino-ipzs** [comment]
Closed via #174
