### ISSUE TITLE
[credential_definition] type -> vct for sd-jwt and doctype for mdoc cbor

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#171]
see https://github.com/italia/eudi-wallet-it-docs/pull/166#issuecomment-1824572218

**Comment by peppelinux** [comment]
See https://github.com/italia/eudi-wallet-it-docs/pull/170

**Comment by fmarino-ipzs** [comment]
see also my comment https://github.com/italia/eudi-wallet-it-docs/pull/166#issuecomment-1824600299

**Comment by peppelinux** [comment]
@fmarino-ipzs it's not our choice, this comes from the standards OpenID4VC and HAIP

**Comment by fmarino-ipzs** [comment]
I fully agree that we must follow the standards, but in [OID4VCI ](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-credential-issuer-metadata-2) we have:

`type: REQUIRED. Array designating the types a certain credential type supports according to [[VC_DATA](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#VC_DATA)], Section 4.3.`

Maybe this should be changed accordingly, am I missing something?

**Comment by peppelinux** [comment]
@fmarino-ipzs the type REQUIRED is defined within the appendix E, related to json-ld

[E.1.1. ](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#appendix-E.1.1)[VC Signed as a JWT, Not Using JSON-LD](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-vc-signed-as-a-jwt-not-usin)

this means that this is normative only for that credential format

**Comment by peppelinux** [comment]
Closed by https://github.com/openid/OpenID4VCI/commit/12d5ede25056daba991906e845d80128ad57572c
