### ISSUE TITLE
[SD-JWT] _sd_hash -> sd_hash

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#173]
the nth breaking change do handle

https://github.com/oauth-wg/oauth-selective-disclosure-jwt/commit/7d350e99ace65251e75d8a195ef1446839a2f2eb

**Comment by fmarino-ipzs** [comment]
It seems that the details about the key binding JWT are currently missing in the Presentation Section. We should add these details describing how the Holder includes in the SD-JWT to prove the Key Binding to the Verifier.
@peppelinux ^^^

**Comment by peppelinux** [comment]
we sign the vp using the cnf.jwk contained in sd-jwt

we can support both, the signature of the vp is credential format agnostic

**Comment by peppelinux** [comment]
@m-basili please check that this issue is resolved by https://github.com/italia/eudi-wallet-it-docs/pull/251/files

if yes, please close this issue

**Comment by m-basili** [comment]
This issue is resolved by #251
