### ISSUE TITLE
Universal Link instead of custom url scheme

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#186]
According to the material produced by collegues from PagoPA and the agreement achieved, we have decided to not use custm url schemes with the wallet solution but only universal links.

A section/box must be provided in the wallet solution section, defining the techical details and the rational about this.

see also https://github.com/italia/eudi-wallet-it-docs/pull/176#discussion_r1440492748

**Comment by grausof** [comment]
We need to move this issue to milestone 0.7.0 as it does not impact MVP

**Comment by peppelinux** [comment]
according to the current specs we have removed the custom url scheme with the will to use only the universal links, do we assume to use custom url scheme and reintroduce them in the current specs?

**Comment by grausof** [comment]
> according to the current specs we have removed the custom url scheme with the will to use only the universal links, do we assume to use custom url scheme and reintroduce them in the current specs?

It's okay to leave universal link for now. But we will address how and by whom this universal link must be managed and what it must contain in 0.7.0

**Comment by grausof** [comment]
Cross Device will be addressed in 0.7.0 or later

**Comment by peppelinux** [comment]
Duplicated here: https://github.com/italia/eudi-wallet-it-docs/issues/240
