### ISSUE TITLE
Pid sd-jwt chapter (Marino)

### ISSUE THREAD

**Issue by misillet** [italia/eidas-it-wallet-docs#19]
https://github.com/italia/eidas-it-wallet-docs/blob/0a918c452512f9b77887b2748b75cffb98579558/docs/en/pid-eaa-sd-jwt.rst?plain=1#LL1C1-L1C1

**Comment by peppelinux** [comment]
Done here https://github.com/italia/eidas-it-wallet-docs/pull/28
