### ISSUE TITLE
Remove format from the credential response

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#190]
according to https://github.com/openid/OpenID4VCI/pull/208/files

**Comment by peppelinux** [comment]
it seems to me that this format should not be removed anymore
https://github.com/openid/OpenID4VCI/pull/219

**Comment by fmarino-ipzs** [comment]
@peppelinux , if you agree, I suggest temporarily removing this issue from milestone 0.6, as this is still under discussion. I would keep this on our todo list.

**Comment by peppelinux** [comment]
we can remove it since it was reintroduced again by Torsten, I need to recheck it all before removing it

**Comment by peppelinux** [comment]
Actually, `credential_configuration_id` MUST NOT be present if `format` parameter is present

https://github.com/openid/OpenID4VCI/pull/219/files#diff-1f424614b35a9899813079f1b1f6218631a2aedd993368ccb89bb81a9eda0289R417

the parameter used is decided by the wallet not by the issuer. Therefore our implementation must support both.
I really don't like this.

**Comment by peppelinux** [comment]
Since it is in ID1 I would keep this in 0.6.0

**Comment by peppelinux** [comment]
To be processed when  openid4vci ID-1 will be published.

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-docs/pull/371/files
