### ISSUE TITLE
VC (PID / (Q)EAA) data model update

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eidas-it-wallet-docs#193]
Add a class to categorise data within a credential, distinguishing for instance between "dati personali" (including current_first_name, current_family_name, date_of_birth, place_of_birth, taxpayer_identification_number, ...) and "dati tessera". This will allow the information to be organised in a more readable way at the front-end.

**Comment by fventola-ipzs** [comment]
We can manage this with [SD-JWT VC DM](https://github.com/danielfett/sd-jwt-vc-dm) and [SD-JWT-VC Types](https://github.com/vcstuff/sd-jwt-vc-types)

**Comment by peppelinux** [comment]
We have also moved the IDA information from the issued credential to the VCI metadata and informed the OpenID4IDA WG about this

See: https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/pid-eaa-issuance.rst?plain=1#L1079

this is not intended to be a defintiive solution but at least the decision to not include anymore the IDA within the issued credentials within the current milestones.

**Comment by peppelinux** [comment]
Out of scope for pid data model

the discussion could be made within the context of the credential metadata

@RosaliaGaleano ^
