### ISSUE TITLE
Entity configuration Relying Party update

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eidas-it-wallet-docs#194]
Provide a specific field for the PR to specify the "service purpose" for requesting one or more credentials or attributes. 
Topic to be further explored at the same time as selective disclosure.

**Comment by peppelinux** [comment]
Closed by https://github.com/italia/eudi-wallet-it-docs/pull/220

**Comment by peppelinux** [comment]
@RosaliaGaleano the `presentation_definition` parameter within the RP's metadata, in the Entity Configuration, defines this.
