### ISSUE TITLE
DPoP for Wallet Attestation

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#195]
This proposal represent an important breaking change.

https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/pull/67/files

**Comment by peppelinux** [comment]
a similar discussion was proposed here
https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/issues/45

**Comment by grausof** [comment]
Given that this proposal is still under discussion, I move the milestone to **0.7.0**

**Comment by fmarino-ipzs** [comment]
Is this issue still pending? @peppelinux can we consider it closed based on this PR #138

**Comment by peppelinux** [comment]
untill the dicussion won't be closed in IETF I would not close this otherwise we lost the ref and we might lose an important breakking change

the PR is still (unfortunately) opened in the oauth attestation based client-auth repository

**Comment by peppelinux** [comment]
the client based attestation auth is changed with customized http headers
https://github.com/oauth-wg/draft-ietf-oauth-attestation-based-client-auth/pull/74/files

this issue must be closed and a new one must be open

**Comment by peppelinux** [comment]
The thread continues here: https://github.com/italia/eudi-wallet-it-docs/issues/289
