### ISSUE TITLE
Wallet Attestation request flow with OAuth 2.0 nonce endpoint

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#200]
The steps 6 and 7 should be made according to 
https://github.com/peppelinux/draft-demarco-nonce-endpoint

@rohe do you have any claims or requirements in the http request according to your analysis?

**Comment by grausof** [comment]
I am closing this issue given that the steps you mentioned concern obtaining a nonce from the Integrity Attestation Services made available by **Apple** and **Google**, therefore the endpoints will be the custom ones made available by the two manufacturers. How this will work will be defined [here](https://github.com/italia/eudi-wallet-it-docs/issues/197)
