### ISSUE TITLE
Lifecycle of the Wallet Instance

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#214]
We should define the Wallet Instance lifecycle at least concerning:

1. the relationship with the lifecycle of the PID, if any
2. Wallet Attestation
3. the revocation triggered by 
   - the User (e.g. device lost/stolen)
   - the Wallet Provider (e.g. breaking of cryptographic material, vulnerabilities of some devices, etc.)
4. The relationship with the lifecycle of the other Credential stored in the Wallet Instance, if any

**Comment by grausof** [comment]
There are similar issues:
- https://github.com/italia/eudi-wallet-it-docs/issues/197
- https://github.com/italia/eudi-wallet-it-docs/issues/110 (closed in favor of 197)

I suggest leaving just one.

**Comment by peppelinux** [comment]
The point below still needs to be addressed

> The relationship with the lifecycle of the other Credential stored in the Wallet Instance, if any

moved to https://github.com/italia/eudi-wallet-it-docs/issues/279
