### ISSUE TITLE
Presentation Chapter (Padalino)

### ISSUE THREAD

**Issue by misillet** [italia/eidas-it-wallet-docs#22]
https://github.com/italia/eidas-it-wallet-docs/blob/0a918c452512f9b77887b2748b75cffb98579558/docs/en/presentation.rst?plain=1#L1

**Comment by misillet** [comment]
fa riferimento al documento 
https://collaborationxperience.sharepoint.com/:w:/r/sites/ITEUDIWallet/_layouts/15/Doc.aspx?sourcedoc=%7B1d0db32e-b92f-4ace-a299-f2bbfba258d9%7D&action=default&cid=01ddff91-2f18-4a29-99e2-ef9c15da2a23
da finalizzare a stretto giro

**Comment by peppelinux** [comment]
Done in https://github.com/italia/eidas-it-wallet-docs/pull/31
