### ISSUE TITLE
What to do when revoking an already revoked Credential

### ISSUE THREAD

**Issue by balanza** [italia/eidas-it-wallet-docs#222]
In the [Status Attestation specification](https://github.com/italia/eudi-wallet-it-docs/pull/221) we must be clear on the expected behavior of the API so that implementers can act accordingly.

The scenario is: that **a revocation is requested for an already-revoked Credential**. This could happen for several reasons, for example:
* both the Issuer and the Holder are requesting revocation
* a previous request didn't respond to networking problems, nevertheless, the revocation has been recorded
* the Wallet Instance fails to properly label the Credential as revoked
* ...

I see 2 different approaches, both valid but with a tradeoff:
1. **Idempotence**
The request succeed, and that matches the expectations of the user who wants the Credential to be revoked. On the other side, the user cannot be sure when the Credential has been revoked (it could have just happen or days ago)
_pros_: the user gets what it wants
_cons_: we are hiding some information
2. **Strictness**
The request fails, which is misleading for the user which "fails to accomplish a result because it's already accomplished". The user must inspect the failure details to know it's not a real failure
_pros_:  the request is responded strictly
_cons_: operation ergonomics is bad

**Comment by balanza** [comment]
My thoughts are on option 1, but I'd like to discuss

**Comment by peppelinux** [comment]
unless the credential was not expired the response would return "already revoked"

when the credential result expired, the response would be not found

**Comment by balanza** [comment]
> when the credential result expired, the response would be not found

I agree, good to point out

> unless the credential was not expired the response would return "already revoked"

Does this fall under the **_2. Stricness_** approach? Or is it different?

**Comment by peppelinux** [comment]
@balanza yes it falls under 2.

**Comment by peppelinux** [comment]
See https://datatracker.ietf.org/doc/html/draft-demarco-oauth-status-assertions#name-status-assertion-error

**Comment by m-basili** [comment]
We can close this issue because #308 addresses it. 
@peppelinux, @fmarino-ipzs

**Comment by fmarino-ipzs** [comment]
> We can close this issue because #308 addresses it. @peppelinux, @fmarino-ipzs

I agree, if @peppelinux and @grausof also agree I will close this issue
