### ISSUE TITLE
[Presentation] Error Management

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#224]
Error Management should be added to the Relying Party Section.

**Comment by peppelinux** [comment]
Based on the information in the OpenID for Verifiable Presentations specification, we don't have explicitly details about the errors.

however, I have producesd this PR that aims to close this issue
https://github.com/italia/eudi-wallet-it-docs/pull/226

**Comment by peppelinux** [comment]
Closed by https://github.com/italia/eudi-wallet-it-docs/pull/226
