### ISSUE TITLE
Define the Term Wallet Trust Evidence and WSCA and PoA

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#230]
Don't we still want to introduce the term Wallet Trust Evidence?

_Originally posted by @grausof in https://github.com/italia/eudi-wallet-it-docs/pull/220#discussion_r1512336689_

**Comment by peppelinux** [comment]
and WSCA and Proof of Association.

**Comment by grausof** [comment]
Duplicate of https://github.com/italia/eudi-wallet-it-docs/issues/396
