### ISSUE TITLE
[Wallet Solution] wallet state typo

### ISSUE THREAD

**Issue by damikael** [italia/eidas-it-wallet-docs#239]
https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/wallet-solution.rst?plain=1#L49

Maybe, here it should be: "Once the Wallet Instance is in the **Valid** state"

**Comment by peppelinux** [comment]
@damikael the "Operational" state according to current eIDAS ARF
https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md#424-eudi-wallet-instance-lifecycle
