### ISSUE TITLE
Remove kid from verifiable presentation

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#243]
In the Verifiable Presentation JWS, the `kid` must be removed as we don't have a `kid` in the `cnf.jwk` claim. 

![image](https://github.com/italia/eudi-wallet-it-docs/assets/77629526/cb85d19c-6c0d-4cf5-b2ad-33083b9bf2ba)

**Comment by peppelinux** [comment]
the example given refers to a deprecated approach we had of presenting the credentials within the vp_token array. The VP JWT was an experience designed in a moment where we was waiting for further clarifications about SD-JWT vs W3C VC DT.

The PR that resolves this issue and also remove the cited deprecation is https://github.com/italia/eudi-wallet-it-docs/pull/251
