### ISSUE TITLE
[Wallet Solution - Wallet Instance Lifecycle] Wallet Deactivation

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#253]
Wallet Deactivation section states the following: "Users have the ability to deactivate the Wallet Instance voluntarily. This action removes the operational capabilities of the Wallet Instance and sets it to the Deactivated state. Deactivation provides Users with control over access and usage according to their preferences."
See link [here](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/wallet-solution.rst?plain=1#L64)

Within this context, in addition to user we should clarify that Wallet Providers will be able to deactivate a single wallet instance or every wallet instance with a specific Version (e.g. because a software weakness is found). The wallet itself must include a "mandatory update" capability in this case that will force users to update wallet before any further use.

**Comment by peppelinux** [comment]
please create a PR where an enumeration of the entities that can deactivate a wallet is provided, according to your suggestion you're confirming the user and suggesting to add the wallet provider as well.

while for the mandatory update, I find it very interesting; however there might be legal implications behind this that must be further analyzed

**Comment by cmarco0** [comment]
Do you think this list of entities is satisfactory for resolving the issue?

- **Users**, can deactivate voluntarily their own Wallet Instance.
- **Wallet Providers**, can deactivate a single Wallet Instance or multiple instances of a specific version that is affected by a critical vulnerability.
- **System Administrators**, private or public organizations, can deactivate a Wallet Instance when an employee no longer requires it (e.g., the employee is no longer part of the company)
- **Security Gov Org**, can deactivate a certain Wallet Instance if it was involved in transaction fraud or malicious activities.
