### ISSUE TITLE
[Wallet Solution - Wallet Provider Endopoints] Header 

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#254]
The Value description for  "alg"   Key is   "Algorithm used to verify the token signature (e.g., ES256)."  Link [https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/wallet-solution.rst?plain=1#L88C1-L88C78](url)

It would be preferable to clarify that this Value must be one of the possible values indicated [here ](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/algorithms.html)

**Comment by peppelinux** [comment]
Yes, please provide an editorial review where all the place where the cryptographic algorithms are used must provide a references to the allowed algs

**Comment by peppelinux** [comment]
The editorial review must be accomplished in the form of Pull Request
