### ISSUE TITLE
[Wallet Attestation - Requirements ] Req.2 RESTful Service

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#255]
Requirement 2 specifies that " The Wallet Provider MUST offer a RESTful set of services for issuing the Wallet Attestations." [Link](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/wallet-attestation.rst?plain=1#L26)

It's not clear why this requirement is set here. Is this service supposed to be called by external entities? 

The previous text should be updated as follows:  "The Wallet Provider must offer a set of services, exclusively available to its Wallet Solution instances, for the verification and issuance of Wallet Attestations"

**Comment by peppelinux** [comment]
Agree, please go ahead with a single PR resolving this issue
