### ISSUE TITLE
[Wallet Attestation - Requirements ] Req.4 Wallet Attestation Signature

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#256]
The actual requirement 4 states: " The Wallet Attestation MUST be issued and signed by an accredited and reliable Wallet Provider, thereby providing integrity and authenticity to the attestation." [Link](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/wallet-attestation.rst?plain=1#L28C3-L28C164)

The text could be misleading and should be updated as follows: "The Wallet Attestation must be signed by the SAME Wallet Provider that is authoritative for (thus has issued) that wallet, as indicated by the overseeing Accreditation Body/Authority, so that the Attestation will uniquely bind the Wallet Provider to this Wallet Instance"

**Comment by peppelinux** [comment]
It sounds really resonable. Please provide a PR for this proposal

at the same time, please, bring all your awareness about the evidence that a wallet provider, in particular a public solution, carries the national first level domain (eg: .it) and this imply that a wallet attestation, by disclosing its wallet provider (issuer) discloses also the domain ...
