### ISSUE TITLE
[PID/(Q)EAA Data Model - Parameters] vct

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#260]
The "vct" claim is defined as "Credential type as a string, MUST be set in accordance to the type obtained from the PID/(Q)EAA Issuer metadata...." [Link ](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/pid-eaa-data-model.rst?plain=1#L102)

As there will be large number of credential types, it would be preferable here to refer to the attestation's SCHEMA identifier assigned into the Trust Schema Chain/Registry. This will create a more dynamic approach to credential typology (for example for the same EEA type there could be different schemas in different EU Member States)

**Comment by peppelinux** [comment]
this requirement regarding vct is mandated by the SD-JWT VC specification

while the credential's schema provider  for SD-JWT is going to be defined here: https://github.com/italia/eudi-wallet-it-docs/issues/199

**Comment by peppelinux** [comment]
already there and implemented
