### ISSUE TITLE
[PID/(Q)EAA Data Model - PID Claims] missing element

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#261]
Within PID claims, [Link ](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/pid-eaa-data-model.rst?plain=1#L109) we need to add a reference to the Schema used by the PID.

**Comment by peppelinux** [comment]
I agree that a ref to ARF where the PID data set schema is provided would make sense
