### ISSUE TITLE
[PID/(Q)EAA Data Model - PID Claims] Family name

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#262]
PID Claim given_name AND family_name as defined would bring possible limitations:

1) this requirement could bring to issues when applied to situations where a user may have multiple names/surnames (e.g. see latest Italian legislation on newborns from 2022) and in case of patronimic
2) there's no provision on what would be the corresponding structure for a legal-entity identifier

**Comment by peppelinux** [comment]
This is something already analyzed within the eidas expert group, at the current stage I would suggest to keep the schema already defined for the PID within the ARF v1.3 and newer

**Comment by peppelinux** [comment]
while for the legal-entity identifier I would suggest to open a separate issue

**Comment by pietroACN** [comment]
Created new [issue ](https://github.com/italia/eudi-wallet-it-docs/issues/280)
