### ISSUE TITLE
[PID/(Q)EAA Issuance - Detailed Flow] Discovery

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#263]
The discovery phase is described as "Steps 1-4 (Discovery): The User selects the PID/(Q)EAA Provider using the Wallet Instance, the Metadata for the selected PID/(Q)EAA Provider are processed by the Wallet Instance".

To perform this action there's a need of a Trusted List/Registry of Authorized/Accredited PID/(Q)EAA Providers maintained by a supervisory body/authority, that the instance will need to obtain at this purpose. This Trusted List/Registry will need to include related federation endpoint that the wallet will need to access.

There's also, for cross-border service access, the possibility that a user will need  PID/(Q)EAA from a specific Member State, thus the Trusted List/Registry will need to keep this information as well.

**Comment by peppelinux** [comment]
I suggest to ref the section of the documentation where the trsut evaluation and metadata resolution mechanisms are defined, without exploding too much text in that step number

**Comment by pietroACN** [comment]
In addition  to what Sara added into the PR, the Issue wanted to highlight the need, within the discovery phase of a wallet , to select PID/(Q)EAA Provides only among the ones present into the appropriate Trust Lists. For example, if I need to retrieve a birth attestation, I need to retrieve the list of authorized issuers from the thematic trust list.

**Comment by peppelinux** [comment]
> In addition to what Sara added into the PR, the Issue wanted to highlight the need, within the discovery phase of a wallet , to select PID/(Q)EAA Provides only among the ones present into the appropriate Trust Lists. For example, if I need to retrieve a birth attestation, I need to retrieve the list of authorized issuers from the thematic trust list.

**Comment by SaraConsoliACN** [comment]
> In addition to what Sara added into the PR, the Issue wanted to highlight the need, within the discovery phase of a wallet , to select PID/(Q)EAA Provides only among the ones present into the appropriate Trust Lists. For example, if I need to retrieve a birth attestation, I need to retrieve the list of authorized issuers from the thematic trust list.

I added your suggestion in the PR https://github.com/italia/eudi-wallet-it-docs/pull/309. Please, could you take a look at this to ensure the issue can be closed?
