### ISSUE TITLE
[Credential Lifecycle] - Revocation

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#264]
Within Credential Lifecycle revocation is considered "absolute", for example is described as follows: "A Credential that has been revoked, due to legal requirements, inaccuracy or compromise, is valueless and potentially harmful."  [Link](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/revocation-lists.rst?plain=1#L8)

Credential revocation is not always 'absolute', i.e. a credential can be revoked today (e.g. driving license revoked temporarily by police) but its validity up to the revocation is still correct and any further use should be still allowed provided that the connected status attestation claims that the credential is not valid in a specific timeframe From-To (e.g. 3-months revocation of driving license). 
A covid certificate that has been temporarily revoked can be used anytime to demonstrate for example that before  revocation holder was entitled to perform some public activity.

Revocation therefore must include a Timeframe (From-To), a tipology, and should not invalidate further use of the credential as it may be used to attest activity outside revocation interval.

**Comment by peppelinux** [comment]
we don't want to take into account credential suspections at this stage, a revoked credential is revoked, while if possibile a new one of the same type can be requested and issued, if the requester is eligible in requesting and obtaining it

**Comment by pietroACN** [comment]
Suspension is only one of the 2 problematic elements that were described in this issue.
The major one is related to the fact that the Credential in some cases **must** be considered valid (thus is still accurate, useful and valid) for the period before the revocation: a driving license, revoked due expiration or other reasons, is still Valid for the period **before** the revocation. The inability for user and wallet to present the Credential would limit its rightful & lawful use that depends only from the related Relying Party process and means of use

**Comment by OR13** [comment]
Verifiers / relying parties have the discretion to accept presentations of credentials based on their own policies.
If you wish to provide a "base verifier policy" or recommendations for verifiers operating in a vertical, such as residency, employment or supply chain. That might be better achieved in a standalone document.

**Comment by peppelinux** [comment]
It's up to the RP's internal policy decide the meaning and value of a presented credential, even if suspended, such as a suspended mobile driving license still usable for proofing the over age of the user.

Therefore:

1. RP requests credentials
2. Holder releases them
3. RP evaluates the validity and value of them according to its internal policies

This issue will be resolved with a non-normative section, such as a impl consideration, within the section about the presentation.

**Comment by peppelinux** [comment]
in cases of revoked credential, it's always up to the RP do the evaluation, such as a revocation motivation that might impact on a negative evaluation for particular use-cases of interest for the RP

a revoked MDL still proof the over age of the user, unless the revocation motivation was a fake document and happened for jurisdictional reasons.

**Comment by peppelinux** [comment]
this is accomplished thanks to the detailed status assertions, revocation motivation should be configured there, if any.

**Comment by pietroACN** [comment]
This is correct, through the status assertion we can handle this case
