### ISSUE TITLE
Wallet Instance Attestation with Attestation Based Client Authentication using HTTP headers

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#289]
The Attestation Based Client Authentication has introduced an important breaking change here:
https://github.com/oauth-wg/draft-ietf-oauth-attestation-based-client-auth/pull/74/files

the http post parameters must not be used anymore, the http headers must be used.

**Comment by grausof** [comment]
I think this has a big impact on the issuance flow that will have to be reviewed. On the Wallet Solution side I don't see any big impacts, given how our technical rules are structured.
