### ISSUE TITLE
wallet instance statuses, revocation, and attestation link with PID & EAA

### ISSUE THREAD

**Issue by misillet** [italia/eidas-it-wallet-docs#30]
taking ARF into consideration, we have to define 
- a status diagram for the wallet instance
- the exact link/pointer between wallet instance, pid, eaa (if any)
- the lifecyle of an instance, a pid and an EAA in case of:
- - PID expiration
- - PID revocation (by a third party or by the owner)
- - PID suspention (does it exist?)

**Comment by peppelinux** [comment]
This issue is closed because it must be exploded is specialized issues and with more granularity
