### ISSUE TITLE
Clarification on the aud claim in JWT Request Object

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#316]
In the current version of this spec, the `aud` parameter is defined as the identifier of the PID/(Q)EAA Provider. It’s recommended to use the URL of the specific endpoint that consumes the JWT.

**Comment by peppelinux** [comment]
using the url of the endpoint makes it not fully compliant with openid4vci where the issuer unique identifier is enough.

see the thread below and join in there if possibile for you
https://github.com/openid/OpenID4VCI/issues/265

**Comment by peppelinux** [comment]
In the meeting of 31 July 2024 we have decided to

- align the current issuance documentation with the mandatory usage of the `aud` value set with the endpoint url
