### ISSUE TITLE
fix content-type in status attestation and credential revocation requests

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#322]
The `content-type` in the status attestation and credential revocation request should be changed to `application/json` instead of `application/x-www-urlencoded` in accordance with https://peppelinux.github.io/draft-demarco-oauth-status-assertions/draft-demarco-oauth-status-assertions.html

**Comment by peppelinux** [comment]
Please follow this PR: https://github.com/italia/eudi-wallet-it-docs/pull/308
