### ISSUE TITLE
Add trust checks in the protocol flows

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#332]
We need to incorporate additional information at the protocol level about trust checks, including details on how trust is established, maintained, and verified.

**Comment by peppelinux** [comment]
In the meeting of the 31 July 2024 we have decided that:

- this issues requires further clarifications about the section, and more specifically, the lines of the text where these further clarifications are required
- one or more pull request therefore will resolve this issue

**Comment by peppelinux** [comment]
Linked to this: https://github.com/italia/eudi-wallet-it-docs/issues/292

**Comment by peppelinux** [comment]
In both issuance and presentation sections I will create a section about trust evaluation. In this section there will be a clear distinction between the trust evaluation and the protocol flows.

This brand new section will explain any particular aspect in relation of issuance or presentation within the trust evaluation field, referencing the trust model section for any common aspects like the federation entity discovery process or trust marks evaluation and or any other kind of policy evaluation.
