### ISSUE TITLE
[Status Attestation HTTP Response] - Status Code

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#340]
In the actual description of the Status Attestation HTTP Response Status Codes, we have  the description of the status "404 Not Found" set as "The Digital Credential can not be found by the Issuer."  [here](https://github.com/italia/eudi-wallet-it-docs/blob/4ede4dc8c61a8fe273a8fbdb8587d0906bf4de89/docs/en/revocation-lists.rst?plain=1#L400)

I would suggest to improve the description, including in this return code the cases of "credential_revoked" and "credential_updated" thus changing the description as follows:
"The Digital Credential can not be found by the Issuer, or the Status Attestation cannot be issued because the credential has been revoked or updated."

**Comment by peppelinux** [comment]
we already had this conversation: providing additional information may give the possibility to do information gathering

**Comment by pietroACN** [comment]
Thus the wallet will not be able to return to the user any information on why the status attestation cannot be issued.
As the entire flow is protected by HTTPS, tracking these details would be difficult: unlocking/breaking HTTPS in this case would be costly in relation to the outcome (disclosing these information) and I believe that these additional details are protected enough from any data interception.

**Comment by SaraConsoliACN** [comment]
This issue has been resolved in PR #342.
