### ISSUE TITLE
[Status Assertions] - Credential Data to be stored by its Issuer

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#341]
The Credential Proof of Possession includes the hash value of a Digital Credential to allow Credential Issuer proper attestation binding to the previously issued credential.
As the Status Attestation requires the Credential Issuer to request the Authentic Source to verify the credential and respond with a status information, there's a need for the Credential Issuer to store locally additional information needed by the Authentic Source to perform such verification (driving license verification would for example  require user ID and driving license number).
A large Credential Issuer therefore will need to store, for each credential hash,  a set of extra data, including the type of credential (PersonIdentificationData, EuropeanDisabilityCard, EuropeanHealthInsuranceCard,MDL...) and the corresponding fields required to obtain status verification from the Authentic Source.

To minimize the amount of personal data stored at Credential Issuer side, the Credential Proof of Possession should include some extra information, for example:

1) _The type of credential:_ this allows at Credential Issuer side to avoid linking the credential hash to the typology, thus reducing linking credential owner to it (very sensitive for example in case of Disability Card)
2) _The used Identifier:_ this this allows at Credential Issuer side to avoid linking the credential hash to the owner. 
3) _The document Id:_ the unique identifier of the document the attestation is related to

To improve security,  the previous data can be provided encrypted with the public key of the Credential Issuer.

**Comment by peppelinux** [comment]
> As the Status Attestation requires the Credential Issuer to request the Authentic Source to verify the credential and respond with a status information, there's a need for the Credential Issuer to store locally additional information needed by the Authentic Source to perform such verification (driving license verification would for example require user ID and driving license number).

not necessarly, if the authentic source's entry contained in its response contains a unique identifier, as traditionally required in the databases entries.

we can add this as an implementation consideration

@fmarino-ipzs ^

**Comment by pietroACN** [comment]
As it is, the actual implementation will create a situation where the entire framework will not work properly:
1) Credential Issuer will be forced to store locally privacy-sensitive information about the attestation, thus violating Art5- point 16 of the regulation
2) Will make impossible to issue Status Assertion/Attestation whenever Credential Issuer would change (due to loss of certification or any other reason) as the only entity that would be able to relate the credential hash with additional information would be the Credential Issuer
3) would create a lack-in situation for the AS in relation to the credential issuer

**Comment by SaraConsoliACN** [comment]
This issue could be resolved in PR #343, correct?

**Comment by fmarino-ipzs** [comment]
> As the Status Attestation requires the Credential Issuer to request the Authentic Source to verify the credential and respond with a status information, there's a need for the Credential Issuer to store locally additional information needed by the Authentic Source to perform such verification (driving license verification would for example require user ID and driving license number).

It is an implementation option, which is not required by any protocol for the entire system to work properly. A CI should store locally the hash of the Credential the Credential Type and the User identifier. This is required especially for security reasons (not only for revocation). A CI should provide users with a mechanism to revoke their credentials and be aware of which credentials a user owns. In this way, if an attacker maliciously obtains a credential of a User, this can be detected by the user itself and the credential can be revoked immediately.

Regarding how a CI is informed about the validity status of a given set of data previously fetched from an AS, I see several implementation options and architectural approaches for handling this:
- A pull approach (publish/subscribe or API provided by the CI: When something changes on user data, the AS send a notification to a broker or directly to the CI, and this notification is catched by the CI which revoke that credential and inform the User.
- Pull approach (API provided by the AS): the CI periodically requests a status information to the AS. Credential to the AS. 
- [...]

Those aspects are currently under evaluation, and in any case none of these required some extra storage of personal information (more than it is strictly needed to provide the service to the user securely).

side notes:
- regarding your reference to the art 5 comma 16 the entire sentence says:

>enable privacy preserving techniques which ensure unlikeability, where the attestation of attributes does not require the identification of the user.

I understand that sometimes regulations can be long and difficult to read, but perhaps the last part of the sentence should also have been read because it would have made it clear that your concern was not applicable

- minor note:
>To improve security, the previous data can be provided encrypted with the public key of the Credential Issuer.

The encryption typically is nore related to confidentiality then security.

For these reasons, I propose to close this Issue. A new Issue will be opened ASAP to clarify the interactions between the CI and AS.

**Comment by pietroACN** [comment]
Thank you Francesco for your comments, when as you stated "A CI should store locally the hash of the Credential the Credential Type and the User identifier" this means, in a specific example, that a CI storing a Disability Card for a User Identifier will link the user to a very sensitive information. If the CI holds large amount of data for such service, it would be most likely not in line with either GDPR and eIDAS requirements.

A Certification Unique Identifier (similar to DID ) stored by the CI, without any extra detail (e.g. the certification type) would be enough to guarantee privacy and capability for the user to request status, revocation, etc.

Such Identifier, if handled properly (as for example with the DID document), will allow to guarantee also from user side, proof of possession of the credential so to enforce user identification while requesting its status or revocation.

**Comment by peppelinux** [comment]
Legal team will clarify how the CI handles Holder's data according to the European and national regulation.

**Comment by vcarollo** [comment]
To comply with the GDPR, the credential issuer, as the data controller, must collect and retain only the data strictly necessary to achieve the stated purposes. The credential issuer must therefore ensure that only essential data is stored, and, where possible, consider using technologies that enable pseudonymization or anonymization. It is evident that if the credential issuer is to guarantee credential revocation, they must keep a complete record of the data necessary for revocation, even in the absence of the credential being revoked. Privacy is respected through encryption policies and data retention practices that adhere to users' rights, including the right to erasure. The example of the Disability Card is not relevant here, as it involves the digitalization of existing documents currently in use in Italy, which is different from issuing an electronic Attestation of attributes.

**Comment by pietroACN** [comment]
thanks for the update, I notice that:

1) Credential Issuer is most likely a Joint Controller (see [here](https://www.erdalreview.eu/free-download/97912599475299.pdf))
2) the statement "It is evident that if the credential issuer is to guarantee credential revocation, they must keep a complete record of the data necessary for revocation, even in the absence of the credential being revoked" is incorrect as to guarantee credential revocation the storage _complete record_ of the data is not necessary
3) I do not understand the differentiation of Disability Card as this is exactly an EAA as all the others

**Comment by peppelinux** [comment]
1. Wallet architectures do not necessarily use blockchains. The term "decentralized" is relative, as a blockchain is a unique ledger distributed across multiple nodes. Decentralization is more about administrative governance than the technology or protocols used. For example, eIDAS is not decentralized but is distributed across multiple member states according to shared regulations. Each citizen receives their identity, and thus their digital identity, issued by a central authority, local to a member state. Wallet architectures enhance privacy, security, and user experience, by keeping the traditional approach of data handling according to clear responsabilities,  ownership and division of powers.

2.  "Complete" means adequate, not exceeding the scope of data handling. An authentic source that signals a change in user data must notify the credential issuer, who needs to know which issued credentials are linked to that user. Processing personal data is a significant administrative responsibility and a service to citizens. It is required to maintain citizens' trust in public services.

3. It is unclear who introduced the disability card as an example. The proposed data handling approach applies to all issued credentials, whether they are EAA or PID.
