### ISSUE TITLE
Wallet Provider backend's many names

### ISSUE THREAD

**Issue by rohe** [italia/eidas-it-wallet-docs#344]
Some times called Wallet Provider some times Wallet Provider Backend.
I think they are one and the same entity so just choose one name and stay with it.

**Comment by cmarco0** [comment]
In my opinion, distinguishing between "wallet provider" and "wallet provider backend" can be useful to clarify exactly which aspect of the service is being discussed.

If it makes sense, it would also be reasonable to include its definition in the Defined Terms chapter.

**Comment by rohe** [comment]
If it is as you say beneficial to use Wallet Provider and Wallet Provider Backend in different contexts then please do so. 
But then as you say it should be made clear what the difference between them are in the Defined Terms chapter.

**Comment by peppelinux** [comment]
@cmarco0 Wallet Provider is an entity and a defined term, Wallet Backend refers to the Wallet Provider's endpoints, therefore for the resolution of this issue all the occurrence of the term Wallet Backend should be renamed to Wallet Provider Backend

@grausof WDYT? ^
