### ISSUE TITLE
Device check

### ISSUE THREAD

**Issue by rohe** [italia/eidas-it-wallet-docs#350]
In the flow chart in **Wallet Instance Initialization and Registration** the wallet checks if the Device Integrity Service (DIS) is available.

In the text description of step 2 there is also the check whether the device meets the minimum security requirement which is not represented in the flowchart.

Is this done in a call to the DIS directly after the availability is verified or is part of steps 7-8 ?

If the later then the second bullet point in Step 2 should probably be removed.

**Comment by grausof** [comment]
No, it's a preliminary check done in step 2. I've clarified the flow chart better here: https://github.com/italia/eudi-wallet-it-docs/pull/431
