### ISSUE TITLE
[Relying Party Solution - Remote Flow - Authorization Response Details]

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#359]
In this process the Wallet Instance sends the Authorization Response to the Relying Party.
It would be necessary to clarify the "response " format changing the example set [here ](https://github.com/italia/eudi-wallet-it-docs/blob/1cdf40bb3e4cac2627acb2668c797d3e0a6ae759/docs/en/remote-flow.rst?plain=1#L445) from "Below is a non-normative example of the decrypted JSON response content" to "Below is a non-normative example of the decrypted payload of the JWT, before base64url encoding and signing"

**Comment by Zicchio** [comment]
> "Below is a non-normative example of the decrypted payload of the JWT, before base64url encoding and ***signing***

(emphasis mine)

Unleass I am missing something (which might indeed be the case), the current version of the specifications does not suggest that the Authorization Response is signed. 
OIDC4VP allows as an option encrypted but not signed responses [see here](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-signed-and-encrypted-respon:~:text=This%20specification%20also%20defines%20how,JWS%20processing%20MUST%20be%20ignored.) 
and the example [in the italian specifications](https://github.com/italia/eudi-wallet-it-docs/blob/1cdf40bb3e4cac2627acb2668c797d3e0a6ae759/docs/en/remote-flow.rst?plain=1#L449-L471) follows the requirement of an unsigned response, as it doesn't have `iss`, `exp`, or `aud` claims.

If the response is indeed signed, in my opinion the specs should furhter stress it and provide an aligned example.
