### ISSUE TITLE
Credential schema enrichment with verifiable graphic element

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#362]
We have to propose an enrichment of the current credential schema including a graphic element, cryptographically verifiable 

this proposal starts with the evaluation of implementing trust marks, such as in the form of a qrcode, that enable the cryptographic validation and also the human representation of the verifiable element

**Comment by peppelinux** [comment]
the credential configuration in the CI metadata **is one of the proposal** to represent the credential in the holder UI

**the second proposal** is to embed the graphic style within the credential schema

**Comment by hevelius** [comment]
What do you mean as graphic style in the second proposal? 

In the holder device, the graphics of the credential must be reconstructed starting from the base image and inserting the various textual elements promptly (x,y coordinates) so building an ad-hoc template. The main problem with the two proposals made is that in the event of a change in one or both objects (graphics and metadata) we would have a non-aligned template in the app.

**Comment by peppelinux** [comment]
the two proposal are exclusive, DTD and IPZS agreed on the first one, with the graphic styles within the metadata, while the second proposal was brought by pagopa during the editor's call

**Comment by peppelinux** [comment]
During the editor's call of the 17 July we have decided that:

- CI metadata SHOULD provide the graphic properties to represents the credentials within each wallet instances
- WI SHOULD use the CI metadata graphic properties to represents the credentials

This issue aims to be resolved by extending the CI metadata

**Comment by peppelinux** [comment]
Linked to https://github.com/italia/eudi-wallet-it-docs/issues/199

**Comment by m-basili** [comment]
Is this related to what we have already introduced inside **vc_claims** in the  Section **Digital Credential Metadata Type**? https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/pid-eaa-data-model.html#digital-credential-metadata-type

**Comment by peppelinux** [comment]
yes @m-basili, it is.

unfortunately it is only for sd-jwt-vc

anyway the scope of this issue was to enable graphically verifiable trust marks for the credentials, something that is now implemented differently and without any impacts on the openid4vci and or sd-jwt-vci specs

therefore this issue can be closed.
