### ISSUE TITLE
Claims carried from the attestation request to the attestation

### ISSUE THREAD

**Issue by rohe** [italia/eidas-it-wallet-docs#365]
According to the spec the body of the Wallet Attestation JWT MUST contain among other claims:

- authorization_endpoint
- response_types_supported
- response_modes_supported
- vp_formats_supported
- request_object_signing_alg_values_supported
- presentation_definition_uri_supported

The only way the wallet provider can have gotten this information is by the attestation request and there the claims above are
not listed as required.
A slight mismatch. 
Either the above listed claims should be required in both the request and the assertion or they should be optional.

**Comment by grausof** [comment]
Right, you are right. Only `vp_formats_supported` was already integrated. Fixed by https://github.com/italia/eudi-wallet-it-docs/pull/430
