### ISSUE TITLE
[Relying Party Solution] [Remote Flow] Possibile imprecisione al termine del flusso di autenticazione

### ISSUE THREAD

**Issue by Zicchio** [italia/eidas-it-wallet-docs#386]
Al termine del flusso di autenticazione del Relying Party, il grafico del flusso di autenticazione suggerisce che il Relying Party risponde al Walllet fornendo **sempre** un redirect URI, sia nel caso cross device che nel caso same device - step descritto qui
https://github.com/italia/eudi-wallet-it-docs/blob/17cbee313217225dfb53394683027cd3516a8cda/docs/en/remote-flow.rst?plain=1#L72-L73

Tuttavia questo comportamento mi sembra abbastanza inusuale per due motivi:
1. La Wallet Instance quando riceve un redirect uri DEVE reindirizzare lo user agent su questo URI ([fonte](https://github.com/italia/eudi-wallet-it-docs/blob/17cbee313217225dfb53394683027cd3516a8cda/docs/en/remote-flow.rst?plain=1#L542)), comportamento che secondo me è abbastanza inaspettato nel caso cross device in quanto le interazioni per la prosecuzione delle operazioni ("accesso alla risorsa protetta") avvengono nello user agent dell'RP, non in quello della Wallet Instance
2. Il lessico di oid4vp draft21 e delle specifiche italiane suggerisce che ci sono casi il cui il redirect URI non viene trasmesso (si veda [qui](https://github.com/italia/eudi-wallet-it-docs/blob/17cbee313217225dfb53394683027cd3516a8cda/docs/en/remote-flow.rst?plain=1#L542) e [qui](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-response-mode-direct_post:~:text=from%20the%20endpoint%3A-,redirect_uri%3A,present%20the%20Wallet%20MUST%20redirect%20the%20User%20Agent%20to%20this%20URI,-.%20This%20allows%20the))

Forse erroneamente io concludo che il possibile comportamento attesso sia quello di fornire il redirect uri alla wallet instance solo nel caso del flusso same device, mentre nel caso cross device la risposta potrebbe essere un generico OK 200 senza content (o almeno, *senza redirect_uri*).
In altre parole, leggendo le specifiche mi aspetto una un flusso che termina all'incirca in questo modo (scusate lo schema grezzo, non ho familiarità con tools più idonei)

![Presentazione senza titolo](https://github.com/user-attachments/assets/7ed52372-1bce-4423-81b9-374331cd88fa)

La mia conclusione è corretta o invece come da specifiche correnti al termine del flusso viene emesso viene trasmesso al Wallet un redirect URI sia nel caso cross device che nel caso same device?

**Comment by peppelinux** [comment]
[here](https://www.plantuml.com/plantuml/uml/ZLPDRnit4BtpLmpKGst3Tftq9i157DUrdRIrQYdn8Gu4YZkIM5FabX-hk4N_UuQabk36EaG80fYQz-RDcnbIRvpdreUDOZnueyDcWPOnTY6yiJ3wuD2EW3i8Z2tCbtpmeuDViPC2tGX--5skrlwj2iXQuf52jbnx63rmfT33hIPwBJ1nR8SXWQXE-0grpnauGzq0PHc6tQDwbde54pfyJf4TCiQ5bnttIC82dFn2w34yu0AcQACoqBoJA-wbqLKePmtMG1wH7OxX7ly9w3nChF4eF3PquaomWZATdzCnEfAPw62ovWxX_BpmHZqTzbIN5kCPXwCZHmWyEeAEapsFUc42rUSDbC8z26EUv1wupOBcmKgmlPGE-qh_khyq3SBTFTpCPXCIsqXBkk7WvxFNXx2LVlseXPAKOIwRuvhj69AgO_XK7SutwDUc-GoV2cZkn1et-9aSg-kCdvKreIMXnlLp04QhvvsTOGpJjTc2NsCliwLQ1yxpRzf7iEqOxbhK2VRDx01lssDGHd05F520zbBarjQaXPFcR0kPSYgu9XKGPPJ3go_UKcnAHPF6gNYq3fRMRE9PYKVTi0B2s4GYT-1jS3vvdAABO_lCOrnva4juwJL81mvtF9ExwOm1VRRz6BJMTB91rtj18Dvmpy4RoZgS3zBP6gbzOgYR1VGfarLLK7diKMWPZHMyvGkff9Ve62g7to7x-ce6ne8s7jgy8QogeKVdV4wkD3Rz6PZ5toXyyNnlFRa17VRpiPVYnNo-RDZW0e4_UYUvRg0rIWg9hg0-efNBvvIA-s0HpBAIN-w9kvoxeBYIJRMs5FbnSk0ESq0O5zpIM116Hwlshi2bqKjfDzWC9xjO6WS5BW9rmif_qmeGjMiZ8ppgt9MkdNlpXBfiUblTNdCN5XlfN5oU_VVNrSwtM7QsG_A5mk4Tc18KK6L0DLeNtgFByQSaBlzP1qpoZ5iIBbtSHD-x_HlISKBITzIdlRU2T6doB7OafZcjrEnINLgYqLvo1RVE1RGmYwkxeooItptCODhtks8XUGAToqjUg1Ypb1N1T6WfZDw_s-kRsVNzrTMVR3zYpE1oZU89Reng2FGUd-6jr0sDP192A2gR_asCSvXQGv0J28uYyYKL5ZIcy4J0_8P87S_h0hs1BerkRjiaT-YKCPYjKGDMLruZdL36OGFSUoiNmQCRWqWIvHB8vRAHqb9KNXQBm3ikLPo5k9Z91LRPzQ4j0n1_8y2k53Z8Jno4z7rp26ouilrxCkKRh9-JQl7Z6_VJgzDNyFhi3ExUKmF_6zdyvAKROpI6jVUjWs1LtW6xMugvC0t2_xizvAJIPOarlDQp7VnQe3e7pzttwIk_Ayex_Muwtit0yFtA6me7aQ3SQwc0RDhXYntTbN6nZsObEzGPdWXZxUuO0iKfHIFGfdOQ2ow8EAVBe8Qlyh0ngVetz5_OgAy0) the fix

the PR will bring this fix in the seq diagram and the update of the steps descriptions as well
