### ISSUE TITLE
Don't redefine stuffs in the issuance introductionary section

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#392]
@fmarino-ipzs we should not re-define stuffs already defined in the defined terms section.

@m-basili ^

_Originally posted by @peppelinux in https://github.com/italia/eudi-wallet-it-docs/pull/387#discussion_r1736236829_

**Comment by m-basili** [comment]
@peppelinux, I start working on it. As soon as possibile I will provide a PR.

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-docs/pull/405
