### ISSUE TITLE
Some terms need to be aligned with EUDIW Implementing Acts

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#396]
‘wallet secure cryptographic application’ means an application that manages critical assets by using the cryptographic functions provided by the wallet secure cryptographic device; 

‘wallet instance’ means the application installed and configured on a wallet user’s device or environment, which is part of a wallet unit, and that the wallet user uses to interact with the wallet unit; 

‘wallet unit’ means a unique configuration of a wallet solution that includes wallet instances, wallet secure cryptographic applications and wallet secure cryptographic devices provided by a wallet provider to an individual wallet user; 

‘wallet unit attestation’ means a data object that describes the components of the wallet unit, allow authentication and validation of those components and are cryptographically bound to wallet secure cryptographic devices;

**Comment by grausof** [comment]
New terms from the latest draft:

`wallet solution` means a combination of software, hardware, services, settings, and configurations, including wallet instances, one or more wallet secure cryptographic applications and one or more wallet secure cryptographic devices; 

`wallet instance` means the application installed and configured on a wallet user’s device or environment, which is part of a wallet unit, and that the wallet user uses to interact with the wallet unit; 

`wallet unit` means a unique configuration of a wallet solution that includes wallet instances, wallet secure cryptographic applications and wallet secure cryptographic devices provided by a wallet provider to an individual wallet user; 

`wallet provider` means a natural or legal person who provides wallet solutions; 

`wallet user` means a user who is in control of the wallet unit; 

`wallet secure cryptographic application` means an application that manages critical assets by being linked to and using the cryptographic functions provided by the wallet secure cryptographic device; 

`wallet secure cryptographic device` means a tamper-resistant device that provides an environment that is linked to and used by the wallet secure cryptographic application to protect critical assets and provide cryptographic functions for the secure execution of critical operations; 

`critical assets` means assets within or in relation to a wallet unit of such extraordinary importance that their incapacitation or destruction would have a very serious, debilitating effect on the ability to rely on the wallet unit; 

`provider of person identification data` means a natural or legal person responsible for issuing and revoking the person identification data and ensuring that the person identification data of a user is cryptographically bound to a wallet unit.
