### ISSUE TITLE
Remove format parameter in the Credential Response Example

### ISSUE THREAD

**Issue by m-basili** [italia/eidas-it-wallet-docs#409]
In the example of Credential Response is present "format" parameter that should be removed.

{
    **"format": "vc+sd-jwt"**,
    "credential": "...",
    "c_nonce": "ff_EtUQs0ieiIS1NYNBHEQSoy3ct4gpy-89JKwHilrT",
    "c_nonce_expires_in": 86400,
    "notification_id": "dab8ef51-fb43-43a5-a5c1-247c93ddb942"
}

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-docs/pull/410
