### ISSUE TITLE
Revocation Flows - Revocation Request by Wallet Instance - Step 2 (PoP Verification) - Editorial Changes

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#424]
The actual text states:

Step 2 (PoP verification): The Credential Issuer verifies the signature of the PoP using the the confirmation method that was attested in the issued Digital Credential. If the verification is successful, it means that the Wallet Instance owns the private keys associated with the Digital Credential, and therefore is entitled to request its revocation.

We propose to change "PoP" with "revocation_assertion_requests object"

Final Text would look like:

Step 2 (Revocation Assertion Request verification): The Credential Issuer verifies the signature of the revocation_assertion_requests object using the the confirmation method that was attested in the issued Digital Credential. If the verification is successful, it means that the Wallet Instance owns the private keys associated with the Digital Credential, and therefore is entitled to request its revocation.

**Comment by peppelinux** [comment]
ok

**Comment by peppelinux** [comment]
Fatto qui: https://github.com/italia/eudi-wallet-it-docs/pull/426
