### ISSUE TITLE
Better generalization about trust frameworks and examples using openid federation

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#450]
We need ref to the section describing how openid federation is used, therefore using the refs to the section about the trust infrastructure and removing all these explicit mentions to openid federation.

in the trust infrastructure section we use openid federation and we'll introduce all the required harmonization with x.509 during the milestone 0.9.0

for clarity, we can use example "such as using openid federation ... as defined ..."

_Originally posted by @peppelinux in https://github.com/italia/eudi-wallet-it-docs/pull/444#discussion_r1802775232_

**Comment by fmarino-ipzs** [comment]
solved by https://github.com/italia/eudi-wallet-it-docs/pull/444
