### ISSUE TITLE
OpenID for Verifiable Presentations - draft 21

### ISSUE THREAD

**Issue by stedcl** [italia/eidas-it-wallet-docs#454]
The spec 0.8.1 seems to refer OpenID for Verifiable Presentations - draft 20.
Why not draft 21?

**Comment by peppelinux** [comment]
because draft 21 was not released at the time when we have released 0.8.1

**Comment by peppelinux** [comment]
actually we should align to OpenID4VP Draft 22
https://openid.net/specs/openid-4-verifiable-presentations-1_0.html

**Comment by grausof** [comment]
Closed in favor of https://github.com/italia/eudi-wallet-it-docs/issues/473
