### ISSUE TITLE
Viewing credentials offline

### ISSUE THREAD

**Issue by grausof** [italia/eidas-it-wallet-docs#469]
The Wallet Instance requires the credentials obtained even in offline mode (it is not the presentation). What are the requirements that you want to meet to have this display? How can we ensure that the credential is authentic even if the device is offline and the app has been closed for a long time? What happens if the device has been turned off for a long time and then turned on again without a connection?

Let's use this issue to discuss it.

**Comment by peppelinux** [comment]
I didn't get the first part of the description of this issue, I try to put some points to facilitate further clarifications.

> The Wallet Provider requires the credentials obtained even in offline mode

1. The Wallet Provider doesn't request nor obtain credentials. Wallet Instance does.

> How can we ensure that the credential is authentic even if the device is offline and the app has been closed for a long time?

2. revocation statuses can only be obtained using a broadband internet connection.
