### ISSUE TITLE
Iss in the Wallet Instance Attestation Request should be the same as sub in Response 

### ISSUE THREAD

**Issue by rohe** [italia/eidas-it-wallet-docs#52]
**iss** in the Wallet Instance Attestation Request payload is defined as:
`The thumbprint of the JWK of the Wallet Instance or which the attestation is  being requested.`

In the payload of the Wallet Instance Attestation **sub** is defined as:
`The public url of the issuer concatenated with the thumbprint of the JWK of the Wallet Instance for which the attestation is being issued.`

Shouldn't they be the same ?

**Comment by peppelinux** [comment]
Thank you Roland, fixed here: https://github.com/italia/eidas-it-wallet-docs/pull/53

**Comment by peppelinux** [comment]
done here https://github.com/italia/eidas-it-wallet-docs/pull/53
