### ISSUE TITLE
Wallet Instance Attestation Request: sub -> aud

### ISSUE THREAD

**Issue by Sh-Amir** [italia/eidas-it-wallet-docs#58]
The `sub` claim value in the Wallet Instance Attestation request is assigned wrongly to `The public url of the Wallet
Provider` value. As mentioned by `RFC7519`, this value should "identify the principal that is the subject of the JWT" which is the Wallet Instance, not the Wallet Provider. I think if you want to define the recipients that the JWT is intended for, then we should use `aud` if I am not mistaken.

**Comment by grausof** [comment]
@peppelinux

**Comment by fmarino-ipzs** [comment]
Yes @asharif1990 I agree with you. sub value is the same of the iss value. Or we can omit it. In any case the wallet provider must be in the aud field.

**Comment by peppelinux** [comment]
actually the WAI has in the sub value one of the unique identifier of the wallet instance (jwk thumbprint)
https://github.com/italia/eidas-it-wallet-docs/blob/versione-corrente/docs/en/wallet-instance-attestation.rst#payload-2

I agree that in the WAI request the sub must be the thumbprint of the wallet instance jwk as well

**Comment by peppelinux** [comment]
It seems to me that this issue was already revolved, as we can read here
https://github.com/italia/eidas-it-wallet-docs/blob/versione-corrente/docs/en/wallet-instance-attestation.rst#format-of-the-wallet-instance-attestation

**Comment by peppelinux** [comment]
Done here https://github.com/italia/eidas-it-wallet-docs/pull/60/commits/92d4357147cf29062c63b3618f7b4d0721aa4c76
