### ISSUE TITLE
PID `tax_id_code` misspelled with `tax_id_number`

### ISSUE THREAD

**Issue by balanza** [italia/eidas-it-wallet-docs#63]
In https://italia.github.io/eidas-it-wallet-docs/en/pid-data-model.html we referenced the same attribute using two different names:
* `tax_id_number` in the plain PID example
* `tax_id_code` in both the disclosure and the SD-JWT token

I advocate we use the same. Which one should we use?

**Comment by balanza** [comment]
I'd go for `tax_id_code`

**Comment by peppelinux** [comment]
`tax_id_code` since it is a code, mixed numbers and letters, and not a number
