### ISSUE TITLE
Wallet Instance Attestation security attrs

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#68]
According to [oid4vc-haip-sd-jwt-vc](https://vcstuff.github.io/oid4vc-haip-sd-jwt-vc/draft-oid4vc-haip-sd-jwt-vc.html) the WAI should explicitly give the key storage method type and the local user authentication mechanisms, as the example below

````
  "key_type": "STRONGBOX",
  "user_authentication": "APP_PIN_6_DIGITS",
````

I find these information useful and I agree this

**Comment by grausof** [comment]
The WIA is issued by the Wallet Provider's backend. Even if the wallet provider is able to understand whether the app is genuine or not (through a system that we will define) it has no way of verifying whether the information sent by the app relating to the `key_type` and `user_authentication` are true or not. So I don't see any added value

**Comment by grausof** [comment]
Based on this:

> ne abbiamo parlato anche con bundes e la soluzioen migliore è rimuoverle e lavorare con il nostro attested_security_context (che verrà rinominato in "aal" come da NIST)

I think we can close this issue! 

CC @peppelinux

**Comment by peppelinux** [comment]
According to https://github.com/vcstuff/oid4vc-haip-sd-jwt-vc/pull/52/files#diff-a99995e257fff0f7a2ffc150370efce1818b9c1622a50f0187b99e122fc24944R158

we're aware that these sec attrs may be included in the WIA while the `attested_security_context` should be renamed to `aal` according to [NIST 800-63b](https://pages.nist.gov/800-63-3-Implementation-Resources/63B/AAL/) 

@fmarino-ipzs ^

**Comment by Sh-Amir** [comment]
> The WIA is issued by the Wallet Provider's backend. Even if the wallet provider is able to understand whether the app is genuine or not (through a system that we will define) it has no way of verifying whether the information sent by the app relating to the `key_type` and `user_authentication` are true or not. So I don't see any added value

In the case of using the [key attestation](https://developer.android.com/training/articles/security-key-attestation) the wallet provider has a way to verify the information that is provided by the Wallet Instance relating to `key_type` and `user_authentication` are true or not, as the attestation contains a certificate chain that its root certificate is signed with the Google attestation root key. In case, you think that would be useful to consider this information, this might be a way to do it.

**Comment by peppelinux** [comment]
Our sole concern is that key_type and user_authentication discloses devices information like mobile brand while this information should not be disclosed

that's why we kindly suggest to group all the key_type and user_authentication combination in the types recognized within the trust framework that defines `attested_security_context` / `aal`

**Comment by Sh-Amir** [comment]
> Our sole concern is that key_type and user_authentication discloses devices information like mobile brand while this information should not be disclosed
> 
> that's why we kindly suggest to group all the key_type and user_authentication combination in the types recognized within the trust framework that defines `attested_security_context` / `aal`

I agree with not putting them inside the WIA. My suggestion is related to the phase of obtaining the WIA from the Wallet Provider. Providing this information to the Wallet Provider assists the Wallet Provider in setting `attested_security_context` / `aal` claim value in the WIA.

**Comment by balanza** [comment]
Let's assume we put such informations in the WIA. Who would benefit from them?

**Comment by Sh-Amir** [comment]
> Let's assume we put such informations in the WIA. Who would benefit from them?

As I corrected myself [here](https://github.com/italia/eudi-wallet-it-docs/issues/68#issuecomment-1735430842), I said not inside the WIA as `attested_security_context / aal` will serve the same purpose. The same entities who benefit from the `attested_security_context / aal`, Providers and Verifiers.

**Comment by peppelinux** [comment]
A PR will follow when the aal claim will be consolidated in https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/pull/51/files

**Comment by grausof** [comment]
I am closing this issue since the current technical rules already provide for an [aal field](https://github.com/italia/eudi-wallet-it-docs/blob/f4666c9b61c2595af2aebc640824afa4eaa86b5a/docs/en/wallet-attestation.rst?plain=1#L311) as suggested by @asharif1990 and https://github.com/vcstuff/draft-ietf-oauth-attestation-based-client-auth/pull/51
