### ISSUE TITLE
Wallet Instance Attestation - long/short live 

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#73]
We should clarify the lifecycle of the WIA regarding the following points:

- Reliability 
- Privacy
- Offline scenario

**Comment by grausof** [comment]
I imagine that a new Wallet Instance Attestation must be created for each request so it should have a limited duration (1 hour maybe?). This clashes with the offline scenario, but in this case it is possible to use a WIA with a longer maturity (perhaps a few days) but with a lower LoA.

**Comment by peppelinux** [comment]
We agreed that at the current stage the WIA is short lived
