### ISSUE TITLE
RP Solution - same device flow

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#74]
In the (Q)EAA Issance flow as defined in the PR #70, we require the Issuer to perform a PID presentation request to the Wallet Instance according to [[OpenID4VP](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html)] following a same-device flow. In the current version of the IT Wallet specification we only have defined a cross-device authorization flow. 

We should add technical details in the Same Device Flow Section.

**Comment by peppelinux** [comment]
I have implemented the same-device flow in the RP IAM proxy, according [to OpenID4VP](https://bitbucket.org/openid/connect/src/master/openid-4-verifiable-presentations/openid-4-verifiable-presentations-1_0.md), here:

https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/satosa/backend.py#L160

OpenID4VP says

````
The following non-normative example of an Authorization Request refers to the Authorization Request Object 
from above through the request_uri parameter. The Authorization Request can be displayed to 
the End-User either directly (as a link) or as a QR Code:

https://wallet.example.com?
    client_id=https%3A%2F%2Fclient.example.org%2Fcb
    &request_uri=https%3A%2F%2Fclient.example.org%2F567545564
````

I'll do a PR asap for enabling this in the current specs
