### ISSUE TITLE
Collegamento sbagliato nel file della documentazione relying-party-solution.rst

### ISSUE THREAD

**Issue by PascalDR** [italia/eidas-it-wallet-docs#78]
Nel file [relying-party-solution.rst](https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/relying-party-solution.rst) nella sezione [Authorization Response Details](https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/relying-party-solution.rst#authorization-response-details) il collegamento alla documentazione OPENID4VP punta al file stesso mentre il link corretto dovrebbe essere [questo](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-6.3).

**Comment by peppelinux** [comment]
@PascalDR the link only works in the compiled version, verifiable in the resource below
https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/relying-party-solution.html#authorization-response-details

do you have any proposal to make the link working on both github source rst and compiled version?
If yes please give a proposal
