### ISSUE TITLE
[Wallet Solution] endpoint where the WIA MUST be requested

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#80]
In the current specs we have the token endpoint in the wallet_provider metadata

BUT

we don't define in the section WIA request (wallet instance attestation) to which endpoint the WIA MUST be requested

the non normative examples seems to point to the token endpoint.
IF it is confirmed, we must add normative text and more guidance on that

**Comment by grausof** [comment]
I confirm that the correct endpoint is `/token`

**Comment by peppelinux** [comment]
ok, 

TODO: we should add a normative section that documents the http request ([POST](https://datatracker.ietf.org/doc/html/rfc6749#section-3.2)) to the token endpoint and the client authentication on that (otherwise any anonymous request could obtain a WIA). As Client authentication we should take in account `client_assertion` and `client-assertion-type` (`client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer`).

the authorization grant should make able the wallet provider to be sure that the requesting party is a reliable party. Here we should add some explanatory text for a better guidance to the readers.

**Comment by peppelinux** [comment]
Actually we have this.
![immagine](https://github.com/italia/eudi-wallet-it-docs/assets/1297620/815a7b36-eaee-42b1-b9a4-447cb97c05f2)

We should add a reference to RFC7523 as well, since [we use the flow described in it](https://www.rfc-editor.org/rfc/rfc7523.html#section-4).
