### ISSUE TITLE
[Wallet Solution] grant type review

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#93]
According to https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#uri

in the wallet provider metadata we have `grant_types_supported` with the value `"urn:ietf:params:oauth:client-assertion-type:jwt-key-attestation"` while according to (RFC7523) it should be replaced by `urn:ietf:params:oauth:grant-type:jwt-bearer`

this choice depends by the flow designed for the token endpoint, see #80

**Comment by grausof** [comment]
Fixed in https://github.com/italia/eudi-wallet-it-docs/pull/94
